version: '3.9'

services:

  artifactory:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:latest
    restart: always
    ports:
      - 8081:8081
      - 8082:8082
    volumes:
      - app-data:/var/opt/jfrog/artifactory
  nginx:
    build: nginx
    restart: always
    ports:
      - 80:80
    depends_on: 
      - artifactory

volumes:
  app-data:

networks:
  app_net:
